export const VERSION = 1;
export const clamp = (n,a=0,b=100)=>Math.max(a,Math.min(b,n));
export function random(s){s.meta.rng=(Math.imul(s.meta.rng,1664525)+1013904223)>>>0;return s.meta.rng/4294967296;}
export function createState(data,options={}) {
 const airport=data.airports.find(a=>a.id===options.airportId)||data.airports.find(a=>a.id==='base:gig');
 const scenario=data.scenarios.find(a=>a.id===options.scenario)||data.scenarios[0];
 const cash=Number(options.cash)||data.balance.initialCash;
 return {saveVersion:VERSION,meta:{rng:scenario.seed,id:Date.now().toString(),created:new Date().toISOString()},player:{name:options.name||'Administrador',company:options.company||'Horizonte Aeroportos',goal:options.goal||'Equilibrada',avatar:options.avatar||'avatar_manager'},airport:{id:airport.id,level:1,runwayLength:1800,land:1},world:{minute:360,weather:0,weatherUntil:540,scenario:scenario.id},economy:{cash:cash*scenario.cashMultiplier,initialCash:cash*scenario.cashMultiplier,debt:scenario.debt||0,loanDays:scenario.debt?30:0,rate:data.balance.loanRate,fee:32,ledger:[],today:{income:0,cost:0,investment:0},history:[],insolvent:false},flights:[],contracts:[],airlines:Object.fromEntries(data.airlines.map(a=>[a.id,{relationship:60,history:[],growth:false}])),passengersSummary:{total:0,today:0,queues:{checkin:0,security:0,baggage:0,immigration:0,customs:0},wait:0,satisfaction:82,connections:0,missed:0,segments:{}},staff:Object.fromEntries(['service','security','clean','baggage','maintenance','operations','fire','admin'].map(id=>[id,{count:id==='operations'?3:2,training:1,morale:90,fatigue:0,shifts:[1,1,1,1]}])),construction:[],inventory:Object.fromEntries(['stairs','bus','baggage','fuel','gpu','clean','catering','pushback'].map(id=>[id,{count:2,condition:100}])),buildings:[{id:'terminal-1',type:'terminal',x:4,y:10,rotation:0,condition:100},{id:'checkin-1',type:'checkin',x:7,y:10,rotation:0,condition:100},{id:'security-1',type:'security',x:10,y:10,rotation:0,condition:100},{id:'baggage-1',type:'baggage',x:13,y:10,rotation:0,condition:100},{id:'parking-1',type:'parking',x:4,y:16,rotation:0,condition:100},{id:'access-1',type:'access',x:7,y:16,rotation:0,condition:100},{id:'gate-1',type:'gate',x:6,y:6,rotation:0,condition:100},{id:'gate-2',type:'gate',x:10,y:6,rotation:0,condition:100}],gates:[{id:'gate-1',class:1,x:6,y:6,flightId:null},{id:'gate-2',class:1,x:10,y:6,flightId:null}],maintenance:{runway:100,closedUntil:0},reputation:{global:60,passengers:82,airlines:60,punctuality:100,security:75,infrastructure:30,sustainability:20,reliability:100,public:65,maturity:0},research:[],events:[],statistics:{completed:0,cancelled:0,onTime:0,delayCauses:{},achievements:[],log:[],nextId:1,expansions:0,profitableDays:0},settings:{difficulty:options.difficulty||'Normal',speed:1,advisor:true,reducedMotion:false,contrast:false,scale:1,audio:false,debug:false,realDataEnabled:false},resources:{runways:[],taxi:null},tutorial:0};
}
export function log(s,type,message,payload={}){s.statistics.log.push({minute:s.world.minute,type,message,payload});if(s.statistics.log.length>300)s.statistics.log.shift();}
