import {clamp,random,log} from '../core/state.js';
import {EventBus} from '../core/eventBus.js';
export const FINAL=['DEPARTED','CANCELLED','DIVERTED'];
export const STATES={SCHEDULED:'Programado',INBOUND:'Em rota',APPROACH:'Aproximação',LANDING:'Pousando',RUNWAY_EXIT:'Livrando pista',TAXI_IN:'Táxi de chegada',AT_GATE:'No gate',TURNAROUND:'Em serviço',READY_FOR_PUSHBACK:'Pronto para saída',PUSHBACK:'Pushback',TAXI_OUT:'Táxi de saída',QUEUE_FOR_DEPARTURE:'Fila de decolagem',TAKEOFF:'Decolando',DEPARTED:'Concluído',HOLDING:'Espera aérea',GATE_WAIT:'Aguardando gate',CANCELLED:'Cancelado',DIVERTED:'Desviado'};
export class Engine {
 constructor(data,state){this.d=data;this.s=state;this.bus=new EventBus();}
 airport(){return this.d.airports.find(a=>a.id===this.s.airport.id);}
 aircraft(f){return this.d.aircraft.find(a=>a.id===f.aircraftId);}
 count(type){return this.s.buildings.filter(b=>b.type===type).length;}
 cap(effect){return this.s.buildings.reduce((v,b)=>{const def=this.d.buildings.find(d=>d.id===b.type);return v+(def.effect===effect?def.amount*clamp(b.condition,20,100)/100:0);},0);}
 active(){return this.s.flights.filter(f=>!FINAL.includes(f.state));}
 money(amount,category,note,investment=false){if(!Number.isFinite(amount))throw Error('Transação inválida');const s=this.s;s.economy.cash+=amount;s.economy.ledger.push({minute:s.world.minute,amount,category,note,investment});if(s.economy.ledger.length>600)s.economy.ledger.shift();if(amount>0&&category!=='Financiamento')s.economy.today.income+=amount;if(amount<0){if(investment)s.economy.today.investment-=amount;else s.economy.today.cost-=amount;}this.bus.emit('financeTransaction',{amount,category,note});}
 spend(cost,category,note,investment=false){const c=cost*this.d.balance.difficulty[this.s.settings.difficulty].cost;if(this.s.economy.cash<c)throw Error('Caixa insuficiente para esta decisão.');this.money(-c,category,note,investment);}
 capacity(){const s=this.s;return {checkin:this.cap('checkin')*(s.research.includes('automation')?1.35:1)*this.efficiency('service'),security:this.cap('security')*this.efficiency('security'),baggage:this.cap('baggage')*(s.research.includes('sorting')?1.35:1)*this.efficiency('baggage')*(s.events.some(e=>e.modifier==='baggage')?.5:1),immigration:this.cap('immigration'),customs:this.cap('customs'),terminal:this.cap('terminal'),parking:this.cap('parking'),access:this.cap('access')};}
 efficiency(id){const g=this.s.staff[id],turn=Math.floor((this.s.world.minute%1440)/360);return Math.max(.02,Math.min(1.3,g.count*g.shifts[turn]/2)*g.training*(g.morale/100)*(1-g.fatigue/160)*(this.s.events.some(e=>e.modifier==='staff')?.65:1));}
 zone(x,y){return y<=3?'runway':y<=8?'apron':y<=13?'terminal':x>=18?'service':'landside';}
 buildReason(type,x,y,rotation=0){const s=this.s,d=this.d.buildings.find(b=>b.id===type);if(!d)return 'Estrutura desconhecida.';const w=rotation?1:2,h=rotation?2:1;if(x<1||y<1||x+w>27||y+h>19)return 'Fora do terreno.';if(x+w>(s.airport.land===1?18:28))return 'Compre o terreno de expansão primeiro.';for(let xx=x;xx<x+w;xx++)for(let yy=y;yy<y+h;yy++)if(this.zone(xx,yy)!==d.zone)return `Construa na zona ${d.zone}.`;if(s.airport.level<d.level)return `Requer nível ${d.level}.`;if(type==='runway'&&this.count('runway')+1>=this.airport().maxRunways)return 'Limite de pistas deste aeroporto atingido.';if(s.buildings.concat(s.construction.filter(c=>!['CANCELLED','ACTIVE'].includes(c.state))).some(b=>{const bw=b.rotation?1:2,bh=b.rotation?2:1;return x<b.x+bw&&x+w>b.x&&y<b.y+bh&&y+h>b.y;}))return 'Espaço ocupado por estrutura ou obra.';return '';}
 build(type,x,y,rotation=0){const reason=this.buildReason(type,x,y,rotation);if(reason)throw Error(reason);const d=this.d.buildings.find(b=>b.id===type);this.s.construction.push({id:'build-'+this.s.statistics.nextId++,type,x,y,rotation,progress:0,state:'PLANNED',cost:d.cost,duration:d.duration});const c=this.s.construction.at(-1);try{this.spend(c.cost,'Obras',d.name,true);}catch(e){this.s.construction.pop();throw e;}c.state='FUNDED';log(this.s,'constructionFunded',d.name);}
 constructionAction(id,action){const c=this.s.construction.find(c=>c.id===id);if(!c||['ACTIVE','CANCELLED'].includes(c.state))throw Error('Obra indisponível.');if(action==='cancel'){c.state='CANCELLED';this.money(c.cost*(1-c.progress/c.duration)*.5,'Reembolso','Cancelamento de obra');}else c.state=c.state==='PAUSED'?'BUILDING':'PAUSED';}
 expandLand(){if(this.s.airport.land>=2)throw Error('Todo o terreno já foi adquirido.');this.spend(this.d.balance.landPrice*this.airport().landCost,'Terreno','Parcela leste',true);this.s.airport.land=2;}
 upgradeRunway(){if(this.s.airport.runwayLength>=3800)throw Error('Comprimento máximo atingido.');if(this.s.maintenance.closedUntil>this.s.world.minute)throw Error('Aguarde a intervenção atual.');this.spend(100000,'Pista','Alongamento de 200 metros',true);this.s.airport.runwayLength+=200;this.s.maintenance.closedUntil=this.s.world.minute+120;}
 hire(id,delta){const g=this.s.staff[id];if(!g||g.count+delta<0||g.count+delta>80)throw Error('Quantidade inválida.');if(delta>0)this.spend(500*delta,'Equipe','Recrutamento');g.count+=delta;}
 train(id){const g=this.s.staff[id];if(g.training>=1.5)throw Error('Treinamento máximo atingido.');this.spend(2500*g.count,'Equipe','Treinamento');g.training=Math.min(1.5,g.training+.1);g.morale=clamp(g.morale+5);}
 buyEquipment(id){const e=this.s.inventory[id];if(!e||e.count>=40)throw Error('Limite de equipamentos.');this.spend(18000,'Equipamentos',id,true);e.count++;}
 repair(target){if(target==='runway'){this.spend((100-this.s.maintenance.runway)*this.d.balance.repairCost,'Manutenção','Pista');this.s.maintenance.runway=100;this.s.maintenance.closedUntil=this.s.world.minute+40;return;}const b=this.s.buildings.find(b=>b.id===target)||this.s.inventory[target];if(!b)throw Error('Item ausente.');this.spend((100-b.condition)*120,'Manutenção','Preventiva');b.condition=100;}
 research(id){const d=this.d.research.find(r=>r.id===id);if(!d||this.s.research.includes(id)||this.s.airport.level<d.level||!d.requires.every(r=>this.s.research.includes(r)))throw Error('Pré-requisitos de pesquisa não atendidos.');this.spend(d.cost,'Pesquisa',d.name,true);this.s.research.push(id);}
 loan(){const e=this.s.economy;if(e.debt+200000>this.d.balance.loanLimit)throw Error('Limite de crédito atingido.');e.debt+=200000;e.loanDays=this.d.balance.loanTerm;e.rate=this.d.balance.loanRate*(e.cash<100000?1.5:1)*this.d.balance.difficulty[this.s.settings.difficulty].cost;this.money(200000,'Financiamento','Empréstimo; amortização diária');}
 repay(){const e=this.s.economy;const n=Math.min(e.debt,200000);if(n<=0)throw Error('Sem dívida pendente.');if(e.cash<n)throw Error('Caixa insuficiente.');this.money(-n,'Amortização','Pagamento antecipado',true);e.debt-=n;}
 requirements(airlineId,aircraftId,destination){const s=this.s,a=this.d.airlines.find(a=>a.id===airlineId),p=this.d.aircraft.find(a=>a.id===aircraftId),dest=this.d.airports.find(a=>a.id===destination);const errors=[];if(!a||!p||!dest)return ['Dados da rota inválidos.'];if(dest.id===s.airport.id)errors.push('Escolha outro destino.');if(!a.fleet.includes(p.id))errors.push('Aeronave fora da frota da companhia.');if(s.airport.level<Math.max(a.level,p.level))errors.push(`Requer nível ${Math.max(a.level,p.level)}.`);if(s.reputation.global<a.requirements.reputation)errors.push(`Reputação mínima: ${a.requirements.reputation}.`);if(s.airport.runwayLength<p.runwayRequirement)errors.push(`Pista mínima: ${p.runwayRequirement} m.`);if(!s.gates.some(g=>g.class>=p.size))errors.push(`Falta gate classe ${p.size}.`);if(dest.country!==this.airport().country&&(!this.count('immigration')||!this.count('customs')))errors.push('Requer imigração e alfândega.');if(p.cargo&&!this.count('cargo'))errors.push('Requer terminal de carga.');return errors;}
 negotiate(airlineId,discount){const s=this.s,a=this.d.airlines.find(a=>a.id===airlineId);const interest=clamp(this.airport().demand*15+s.reputation.global*.35+s.reputation.punctuality*.2+s.gates.length*2+(50-s.economy.fee)*a.pricingSensitivity*.3+discount*.7);return {interest,minimumDiscount:interest<55?Math.ceil((55-interest)/.7)+discount:discount,accepted:interest>=55};}
 contract(o){const s=this.s;const errors=this.requirements(o.airlineId,o.aircraftId,o.destination);if(errors.length)throw Error(errors.join(' '));const frequency=Number(o.frequency),hour=Number(o.hour),discount=Number(o.discount);if(!Number.isInteger(frequency)||frequency<1||frequency>8||!Number.isInteger(hour)||hour<0||hour>23||!Number.isFinite(discount)||discount<0||discount>40)throw Error('Proposta inválida.');const negotiation=this.negotiate(o.airlineId,discount);if(!negotiation.accepted)throw Error(`Contraproposta: incentivo mínimo de ${Math.min(40,negotiation.minimumDiscount)}%.`);const c={id:'contract-'+s.statistics.nextId++,airlineId:o.airlineId,aircraftId:o.aircraftId,destination:o.destination,frequency,hour,discount,status:'ACCEPTED',start:s.world.minute,end:s.world.minute+30*1440,lastScheduled:-1,history:[],growth:false};s.contracts.push(c);c.status='ACTIVE';this.scheduleContract(c,true);s.tutorial=Math.max(s.tutorial,2);log(s,'contractAccepted','Nova rota contratada',o);return c;}
 cancelContract(id){const c=this.s.contracts.find(c=>c.id===id);if(!c)throw Error('Contrato ausente.');c.status='CANCELLED';for(const f of this.active().filter(f=>f.contractId===id&&f.state==='SCHEDULED'))this.cancelFlight(f.id);}
 growContract(id){const c=this.s.contracts.find(c=>c.id===id);if(!c?.growth)throw Error('Sem proposta de crescimento.');c.frequency=Math.min(8,c.frequency+1);c.growth=false;c.history.push('Frequência ampliada por desempenho.');}
 renew(id){const c=this.s.contracts.find(c=>c.id===id);if(!c||c.status!=='RENEWAL_PENDING')throw Error('Renovação indisponível.');c.end=this.s.world.minute+30*1440;c.status='ACTIVE';c.history.push('Renovado por 30 dias.');}
 scheduleContract(c,first=false){const s=this.s,day=Math.floor(s.world.minute/1440);if(c.lastScheduled===day)return;c.lastScheduled=day;for(let i=0;i<c.frequency;i++){const at=first?s.world.minute+15+i*60:day*1440+c.hour*60+i*60;if(at<s.world.minute||this.active().length>=this.d.balance.maxActive)continue;const p=this.d.aircraft.find(p=>p.id===c.aircraftId),dest=this.d.airports.find(a=>a.id===c.destination);let demand=this.airport().demand*dest.demand*this.airport().tourism*(.7+s.reputation.global/150)*clamp(1-(s.economy.fee-32)/100,.5,1.5)*(1+.15*Math.sin(day/15))*(this.s.player.goal==='Turístico'?1.15:1);if(s.world.scenario==='tourism')demand*=1.5;if(s.events.some(e=>e.modifier==='demand'))demand*=1.2;if(s.research.includes('forecast'))demand*=1.1;const occupancy=clamp(demand*.55/c.frequency**.18*(.9+random(s)*.2),.2,.98);const pax=Math.floor(p.seats*occupancy);const id='flight-'+s.statistics.nextId++;s.flights.push({id,code:c.airlineId.slice(0,2).toUpperCase()+String(s.statistics.nextId).padStart(3,'0'),contractId:c.id,airlineId:c.airlineId,aircraftId:p.id,destination:c.destination,international:dest.country!==this.airport().country,schedule:{arrival:at,departure:at+75*p.turnaround},state:'SCHEDULED',since:s.world.minute,gateId:null,passengers:pax,occupancy,tonnes:p.cargo?Math.min(this.cap('cargo'),p.tonnes)*occupancy:0,delays:{},tasks:{},arrivalsProcessed:false,paid:false,priority:0});this.bus.emit('flightScheduled',{id});}}
 change(f,state){f.state=state;f.since=this.s.world.minute;log(this.s,'flightState',`${f.code}: ${STATES[state]}`,{id:f.id,state});}
 delay(f,cause){f.delays[cause]=(f.delays[cause]||0)+1;}
 release(f){const s=this.s;for(const g of s.gates)if(g.flightId===f.id)g.flightId=null;s.resources.runways=s.resources.runways.filter(r=>r.flightId!==f.id);if(s.resources.taxi===f.id)s.resources.taxi=null;f.gateId=null;}
 cancelFlight(id,divert=false){const f=this.s.flights.find(f=>f.id===id);if(!f||FINAL.includes(f.state))return;this.release(f);this.change(f,divert?'DIVERTED':'CANCELLED');this.s.statistics.cancelled++;this.s.reputation.airlines=clamp(this.s.reputation.airlines-2);this.money(-this.d.balance.cancellation*this.d.balance.difficulty[this.s.settings.difficulty].penalty,'Penalidades',`${f.code}: ${divert?'desvio':'cancelamento'}`);}
 runway(f){const s=this.s,w=this.d.balance.weather[s.world.weather];if(s.maintenance.closedUntil>s.world.minute||s.maintenance.runway<15||w.ramp===0){this.delay(f,'Clima / pista fechada');return false;}const count=1+this.count('runway');if(s.resources.runways.length>=count){this.delay(f,'Fila de pista');return false;}const factor=s.research.includes('ils')&&w.name==='Neblina'?1.2:w.factor;const duration=Math.ceil(this.d.balance.runwaySeparation*factor/(1+this.count('taxiway')*.15));s.resources.runways.push({flightId:f.id,until:s.world.minute+duration});return true;}
 taxi(f){if(this.s.resources.taxi&&this.s.resources.taxi!==f.id){this.delay(f,'Taxiway ocupada');return false;}this.s.resources.taxi=f.id;return true;}
 tick(minutes=1){for(let i=0;i<minutes;i++)this.minute();}
 minute(){const s=this.s,b=this.d.balance;s.world.minute++;const t=s.world.minute;s.resources.runways=s.resources.runways.filter(r=>r.until>t);this.constructions();if(t>=s.world.weatherUntil){s.world.weather=Math.floor(random(s)*b.weather.length);s.world.weatherUntil=t+b.weatherDuration;if(s.world.scenario==='storm'&&random(s)<.4)s.world.weather=4;}
 s.events=s.events.filter(e=>e.until>t);if(t%240===0&&random(s)<b.eventChance){const d=this.d.events[Math.floor(random(s)*this.d.events.length)];s.events.push({...structuredClone(d),instance:'event-'+s.statistics.nextId++,until:t+d.duration,answered:false});log(s,'incidentStarted',d.name);}
 const usage={};for(const f of this.active().sort((a,b)=>b.priority-a.priority||a.schedule.arrival-b.schedule.arrival))this.flightTick(f,usage);
 this.passengers();if(t%60===0)this.hour();if(t%1440===0)this.day();if(t%15===0)this.reputation();for(const c of s.contracts){if(c.status==='ACTIVE'&&t>=c.end)c.status='RENEWAL_PENDING';if(c.status==='ACTIVE')this.scheduleContract(c);if(c.status==='RENEWAL_PENDING'&&t>c.end+3*1440)c.status='EXPIRED';}this.achievements();}
 constructions(){const s=this.s;for(const c of s.construction){if(c.state==='FUNDED')c.state='BUILDING';if(c.state!=='BUILDING')continue;c.progress++;if(c.progress>=c.duration){c.state='COMPLETED';s.buildings.push({id:c.id,type:c.type,x:c.x,y:c.y,rotation:c.rotation,condition:100});const d=this.d.buildings.find(d=>d.id===c.type);if(d.effect==='gates')s.gates.push({id:c.id,class:d.amount,x:c.x,y:c.y,flightId:null});c.state='ACTIVE';s.statistics.expansions++;log(s,'constructionCompleted',d.name);this.bus.emit('constructionCompleted',{id:c.id});}}}
 flightTick(f,usage){const s=this.s,t=s.world.minute,p=this.aircraft(f),age=t-f.since,b=this.d.balance;
 if(f.state==='SCHEDULED'){if(t>=f.schedule.arrival-10)this.change(f,'INBOUND');return;}
 if(['HOLDING','GATE_WAIT','APPROACH'].includes(f.state)&&t-f.schedule.arrival>b.maxWait){this.cancelFlight(f.id,true);return;}
 switch(f.state){
 case 'INBOUND':if(t>=f.schedule.arrival)this.change(f,'APPROACH');break;
 case 'APPROACH':case 'HOLDING':{const g=s.gates.find(g=>!g.flightId&&g.class>=p.size);if(!g){this.delay(f,'Gate indisponível');if(f.state!=='HOLDING')this.change(f,'HOLDING');break;}if(this.runway(f)){g.flightId=f.id;f.gateId=g.id;this.change(f,'LANDING');}break;}
 case 'LANDING':if(!s.resources.runways.some(r=>r.flightId===f.id))this.change(f,'RUNWAY_EXIT');break;
 case 'RUNWAY_EXIT':if(this.taxi(f))this.change(f,'TAXI_IN');break;
 case 'TAXI_IN':if(age>=b.taxiDuration){s.resources.taxi=null;this.change(f,'AT_GATE');}break;
 case 'AT_GATE':this.change(f,'TURNAROUND');for(const task of b.services)f.tasks[task.id]=0;if(!f.arrivalsProcessed){f.arrivalsProcessed=true;if(!p.cargo){s.passengersSummary.queues.checkin+=f.passengers;s.passengersSummary.queues.baggage+=f.passengers*.8;if(f.international){s.passengersSummary.queues.immigration+=f.passengers;s.passengersSummary.queues.customs+=f.passengers;}}}break;
 case 'TURNAROUND':{let done=true;for(const task of b.services){const target=task.duration*p.turnaround;if(f.tasks[task.id]>=target)continue;done=false;if(!task.depends.every(id=>f.tasks[id]>=b.services.find(q=>q.id===id).duration*p.turnaround))continue;const e=s.inventory[task.equipment],used=usage[task.equipment]||0;if(used>=e.count||e.condition<15){this.delay(f,`Equipamento: ${task.name}`);continue;}if(task.id==='board'&&s.passengersSummary.wait>12){this.delay(f,'Filas no terminal');if(age<120)continue;}if(task.id==='load'&&s.passengersSummary.queues.baggage>this.capacity().baggage){this.delay(f,'Bagagens');if(age<120)continue;}const w=b.weather[s.world.weather];const power=s.events.some(e=>e.modifier==='ramp')&&!s.research.includes('resilience');if(!w.ramp||power){this.delay(f,'Rampa interrompida');continue;}usage[task.equipment]=used+1;const eff=this.efficiency(task.staff);if(eff<.6)this.delay(f,'Equipe insuficiente');f.tasks[task.id]+=eff*(e.condition/100)*w.ramp*(s.research.includes('flow')?1.25:1);if(f.tasks[task.id]>=target)this.bus.emit('serviceCompleted',{flightId:f.id,service:task.id});}if(done)this.change(f,'READY_FOR_PUSHBACK');if(age>b.maxWait*2)this.cancelFlight(f.id);break;}
 case 'READY_FOR_PUSHBACK':if((usage.pushback||0)>=s.inventory.pushback.count||s.inventory.pushback.condition<15){this.delay(f,'Pushback indisponível');break;}if(this.taxi(f)){usage.pushback=(usage.pushback||0)+1;this.change(f,'PUSHBACK');}break;
 case 'PUSHBACK':if(age>=3){const g=s.gates.find(g=>g.id===f.gateId);if(g)g.flightId=null;this.change(f,'TAXI_OUT');}break;
 case 'TAXI_OUT':if(age>=b.taxiDuration){s.resources.taxi=null;this.change(f,'QUEUE_FOR_DEPARTURE');}break;
 case 'QUEUE_FOR_DEPARTURE':if(this.runway(f))this.change(f,'TAKEOFF');break;
 case 'TAKEOFF':if(!s.resources.runways.some(r=>r.flightId===f.id)){this.depart(f);this.release(f);}break;
 }
 }
 depart(f){if(f.paid)return;const s=this.s,p=this.aircraft(f),b=this.d.balance,c=s.contracts.find(c=>c.id===f.contractId);this.change(f,'DEPARTED');f.actualDeparture=s.world.minute;f.late=Math.max(0,f.actualDeparture-f.schedule.departure);if(f.paid)return;f.paid=true;const multiplier=b.difficulty[s.settings.difficulty].revenue*(1-(c?.discount||0)/100);f.revenue=(b.landingFee*p.size+b.gateFee+b.serviceFee+f.passengers*s.economy.fee+f.tonnes*b.cargoFee)*multiplier;this.money(f.revenue,'Voos',`${f.code}: pouso + gate + serviços + ${f.passengers} passageiros + ${f.tonnes.toFixed(1)} t`);s.statistics.completed++;if(f.late<=b.lateTolerance)s.statistics.onTime++;else{for(const [cause,minutes]of Object.entries(f.delays))s.statistics.delayCauses[cause]=(s.statistics.delayCauses[cause]||0)+minutes;this.money(-Math.min(2000,f.late*8),'Penalidades',`${f.code}: ${Math.round(f.late)} min de atraso`);}
 s.passengersSummary.total+=f.passengers;s.passengersSummary.today+=f.passengers;const rel=s.airlines[f.airlineId];rel.relationship=clamp(rel.relationship+(f.late<=15?1:-2));if(s.research.includes('hub')){const onward=this.active().find(q=>q.destination!==f.destination&&q.schedule.departure>s.world.minute+45&&q.schedule.departure<s.world.minute+180);if(onward){const n=Math.floor(f.passengers*.15);if(s.passengersSummary.wait<30&&this.capacity().baggage>100){s.passengersSummary.connections+=n;this.money(n*8,'Conexões',`${f.code} → ${onward.code}`);}else{s.passengersSummary.missed+=n;this.money(-n*12,'Conexões','Assistência por conexão perdida');}}}this.bus.emit('flightDeparted',{id:f.id,revenue:f.revenue});}
 passengers(){const s=this.s,p=s.passengersSummary,c=this.capacity();let maxWait=0;for(const id of Object.keys(p.queues)){const n=Math.min(p.queues[id],c[id]/60);p.queues[id]=Math.max(0,p.queues[id]-n);if(id==='checkin')p.queues.security+=n;maxWait=Math.max(maxWait,c[id]>0?p.queues[id]/c[id]*60:p.queues[id]>0?180:0);}p.wait=maxWait;const crowd=Object.values(p.queues).reduce((a,b)=>a+b,0);const cleaning=this.efficiency('clean');const penalty=Math.min(40,maxWait*.35)+Math.max(0,crowd-c.terminal)/20+Math.max(0,1-cleaning)*18+Math.max(0,crowd-c.access)/50;const bonus=Math.min(12,this.count('lounge')*3+this.count('toilet')*2+this.count('shop')*2);p.satisfaction=clamp(88-penalty+bonus);p.segments={lazer:Math.round(p.today*.35),negócios:Math.round(p.today*.25),famílias:Math.round(p.today*.25),premium:Math.round(p.today*.15),conexão:p.connections};}
 hour(){const s=this.s,b=this.d.balance,activity=this.active().length;for(const g of Object.values(s.staff)){g.fatigue=clamp(g.fatigue+(activity>g.count*2?2:-2),0,60);g.morale=clamp(g.morale+(g.fatigue>30?-.5:.1),35,100);}const wear=b.degrade*(1+activity/10);s.maintenance.runway=clamp(s.maintenance.runway-wear);for(const e of Object.values(s.inventory))e.condition=clamp(e.condition-wear);for(const build of s.buildings)build.condition=clamp(build.condition-wear*.5);const staff=Object.values(s.staff).reduce((n,g)=>n+g.count*b.salary,0)/24;const upkeep=(s.buildings.length*b.buildingUpkeep+Object.values(s.inventory).reduce((n,e)=>n+e.count*b.vehicleUpkeep,0))/24;const utility=b.utility*(1+s.buildings.length/15)*(s.research.includes('electric')?.8:1)/(1+this.count('solar')*.12)/24;const mult=b.difficulty[s.settings.difficulty].cost;this.money(-staff*mult,'Salários','Folha por hora');this.money(-upkeep*mult,'Manutenção','Conservação e frota');this.money(-utility*mult,'Utilidades','Energia, água e acessos');const traffic=s.passengersSummary.today/(1+(s.world.minute%1440)/60);const commercial=(this.count('shop')*Math.min(traffic,80)*4+this.count('lounge')*Math.min(traffic,40)*6)*(s.research.includes('premium')?1.2:1);if(commercial)this.money(commercial,'Comercial','Concessões e salas VIP');const parking=Math.min(traffic,this.cap('parking'))*2;if(parking)this.money(parking,'Estacionamento','Acesso terrestre');if(this.airport().restrictions.nightNoise&&s.world.minute%1440<360&&activity>2)s.reputation.public=clamp(s.reputation.public-.5);}
 day(){const s=this.s,e=s.economy;const profit=e.today.income-e.today.cost;s.statistics.profitableDays=profit>0?s.statistics.profitableDays+1:0;e.history.push({day:Math.floor(s.world.minute/1440),...e.today,profit,passengers:s.passengersSummary.today});if(e.history.length>365)e.history.shift();e.today={income:0,cost:0,investment:0};s.passengersSummary.today=0;if(e.debt>0){const principal=e.debt/Math.max(1,e.loanDays);this.money(-e.debt*e.rate,'Juros','Financiamento diário');this.money(-principal,'Amortização','Parcela diária',true);e.debt=Math.max(0,e.debt-principal);e.loanDays=Math.max(0,e.loanDays-1);}e.insolvent=e.cash< -100000;for(const c of s.contracts.filter(c=>c.status==='ACTIVE')){const rel=s.airlines[c.airlineId];if(rel.relationship<20){c.status='CANCELLED';c.history.push('Companhia encerrou por desempenho.');log(s,'contractCancelled','Companhia encerrou a rota.');}else if(rel.relationship>=65&&s.reputation.punctuality>=75&&c.frequency<8){c.growth=true;rel.growth=true;}}
 if(s.flights.length>500)s.flights=s.flights.filter(f=>!FINAL.includes(f.state)||s.world.minute-f.since<1440);}
 reputation(){const s=this.s,r=s.reputation;r.passengers=s.passengersSummary.satisfaction;r.punctuality=s.statistics.completed?s.statistics.onTime/s.statistics.completed*100:100;r.airlines=Object.values(s.airlines).reduce((n,a)=>n+a.relationship,0)/this.d.airlines.length;r.security=clamp(65+this.count('fire')*7+this.efficiency('security')*10);r.infrastructure=clamp(25+s.buildings.length*2+s.airport.runwayLength/250);r.sustainability=clamp(20+this.count('solar')*12+(s.research.includes('electric')?25:0));r.reliability=clamp(100-s.statistics.cancelled/Math.max(1,s.statistics.completed+s.statistics.cancelled)*100);r.global=(r.passengers+r.punctuality+r.airlines+r.security+r.infrastructure+r.reliability)/6;const financial=clamp(50+s.economy.cash/20000-s.economy.debt/30000);r.maturity=[r.infrastructure,r.reliability,r.global,r.punctuality,r.passengers,financial,clamp(s.contracts.filter(c=>c.status==='ACTIVE').length*12)].reduce((v,n,i)=>v+n*this.d.balance.maturityWeights[i],0);const next=this.d.balance.levelRequirements.find(x=>x.level===s.airport.level+1);if(next&&this.levelChecks(next).every(c=>c.ok)){s.airport.level++;log(s,'levelUp',`Nível ${s.airport.level} conquistado`);this.bus.emit('levelUp',{level:s.airport.level});}}
 levelChecks(n=this.d.balance.levelRequirements.find(x=>x.level===this.s.airport.level+1)){if(!n)return [];const s=this.s;return [{label:`${n.flights} voos concluídos`,ok:s.statistics.completed>=n.flights},{label:`Reputação ${n.rep}`,ok:s.reputation.global>=n.rep},{label:`Terminal ${n.terminal} pax`,ok:this.cap('terminal')>=n.terminal},{label:`Pista ${n.runway} m`,ok:s.airport.runwayLength>=n.runway},{label:`${n.gates} gates`,ok:s.gates.length>=n.gates},{label:`Pontualidade ${n.otp}%`,ok:s.reputation.punctuality>=n.otp},{label:'Caixa positivo',ok:s.economy.cash>0},...(n.level>=5?[{label:'Imigração, alfândega e bombeiros',ok:this.count('immigration')>0&&this.count('customs')>0&&this.count('fire')>0}]:[]),...(n.level>=7?[{label:'Pesquisa de conexões',ok:s.research.includes('hub')}]:[]),...(n.level>=9?[{label:'Duas pistas',ok:this.count('runway')>=1}]:[]),...(n.level===10?[{label:'Sustentabilidade 70+',ok:s.reputation.sustainability>=70}]:[])];}
 achievements(){const s=this.s;for(const [id,ok]of [['Primeiro voo',s.statistics.completed>=1],['Operação pontual',s.statistics.onTime>=5],['Mil passageiros',s.passengersSummary.total>=1000],['Primeira expansão',s.statistics.expansions>=1],['Hub doméstico',s.airport.level>=4],['Portão internacional',s.airport.level>=5],['Gigante dos céus',s.flights.some(f=>f.paid&&this.aircraft(f).size>=3)],['Operação verde',s.reputation.sustainability>=70],['Mega-hub',s.airport.level>=9],['Milhão de passageiros',s.passengersSummary.total>=1000000]])if(ok&&!s.statistics.achievements.includes(id)){s.statistics.achievements.push(id);log(s,'achievement',id);}}
 resolveEvent(id,index){const e=this.s.events.find(e=>e.instance===id);if(!e||e.answered)throw Error('Evento já respondido.');const c=e.choices[index];if(!c)throw Error('Resposta inválida.');if(c.cost)this.spend(c.cost,'Incidentes',e.name);e.answered=true;e.until=this.s.world.minute+Math.ceil((e.until-this.s.world.minute)*c.factor);}
 advisor(){const s=this.s;if(s.economy.insolvent)return 'Operação insolvente. Reduza despesas, renegocie a malha e avalie financiamento.';if(s.passengersSummary.wait>10)return `Fila de ${Math.round(s.passengersSummary.wait)} minutos. Compare check-in, segurança e bagagens antes de expandir.`;if(s.maintenance.runway<60)return 'A condição da pista está caindo. Reserve uma janela para manutenção.';if(s.contracts.length===0)return 'Negocie sua primeira rota em Companhias. A Aurora Regional opera com a infraestrutura inicial.';if(s.statistics.completed===0)return 'Acompanhe o primeiro voo no mapa. Os serviços serão executados automaticamente pela equipe.';if(s.airport.level===1)return 'Complete três voos pontuais para chegar ao nível 2. Cada ampliação aumenta os custos fixos.';return 'Confira os requisitos do próximo nível e mantenha folga de capacidade nos horários de pico.';}
}
