import {FINAL,STATES} from '../systems/engine.js';
export const scenes={overview:['bg_apron','Pátio de operações'],flights:['bg_runway','Movimento aéreo'],airlines:['bg_gate','Novas conexões'],operations:['bg_operations','Operação em solo'],passengers:['bg_checkin','Terminal de passageiros'],staff:['bg_maintenance','Sua equipe'],finance:['bg_menu','Resultado da operação'],commercial:['bg_lounge','Experiência e receita'],infrastructure:['bg_maintenance','Prontos para o próximo voo'],stats:['bg_operations','Desempenho'],research:['bg_tower','O próximo nível'],contracts:['bg_cargo','Sua malha aérea'],settings:['bg_terminal','Sua carreira']};
export const equipmentArt={stairs:'bg_gate',bus:'vehicle_bus',baggage:'bg_baggage',fuel:'vehicle_fuel',gpu:'vehicle_pushback',clean:'bg_terminal',catering:'vehicle_catering',pushback:'vehicle_pushback'};
export function suggestedRoute(e){
 for(const airline of e.d.airlines)for(const plane of airline.fleet){
  const destination=e.d.airports.find(a=>!e.requirements(airline.id,plane,a.id).length);
  if(!destination)continue;
  const discount=Math.max(0,e.negotiate(airline.id,0).minimumDiscount);
  if(discount<=40)return {airlineId:airline.id,aircraftId:plane,destination:destination.id,frequency:2,hour:8,discount};
 }return null;
}
export function nextDecision(e){const s=e.s;
 const broken=Object.entries(s.inventory).find(([,v])=>v.count===0||v.condition<25);
 if(broken)return {title:'Serviço de solo em risco',text:broken[1].count===0?'Falta equipamento para atender os voos.':'A frota precisa de manutenção.',action:'view:operations',label:'Resolver em operações'};
 if(s.events.some(x=>!x.answered))return {title:'Incidente aguardando resposta',text:s.events.find(x=>!x.answered).name,action:'view:operations',label:'Tomar decisão'};
 if(s.maintenance.runway<60)return {title:'Prepare a manutenção',text:'A pista está se desgastando. Planeje uma janela.',action:'view:infrastructure',label:'Ver pista'};
 if(s.passengersSummary.wait>12)return {title:'O terminal está congestionado',text:`Maior fila: ${Math.round(s.passengersSummary.wait)} minutos.`,action:'view:passengers',label:'Ver gargalo'};
 if(!s.contracts.some(c=>c.status==='ACTIVE'))return {title:'Abra sua primeira conexão',text:'Uma proposta compatível com seu aeroporto.',action:'suggest-route',label:'Preparar rota'};
 if(s.statistics.completed<3)return {title:'Conclua seus primeiros voos',text:`${s.statistics.completed} de 3 voos concluídos. Acompanhe os gates.`,action:'advance',label:'Avançar 10 minutos'};
 return {title:'Prepare a próxima expansão',text:`Nível ${s.airport.level} · ${e.levelChecks().filter(c=>c.ok).length}/${e.levelChecks().length} requisitos atendidos.`,action:'view:build',label:'Abrir construção'};
}
export function taskProgress(e,f){const plane=e.aircraft(f),tasks=e.d.balance.services;const total=tasks.reduce((n,t)=>n+t.duration*plane.turnaround,0);return Math.round(tasks.reduce((n,t)=>n+Math.min(f.tasks[t.id]||0,t.duration*plane.turnaround),0)/total*100);}
export function renderExperience(e,{asset,esc,button,money}){const s=e.s,a=e.airport(),next=nextDecision(e),active=e.active();
 const gateCards=s.gates.map((g,i)=>{const f=s.flights.find(f=>f.id===g.flightId);return `<button class="gate-tile ${f?'occupied':''}" data-action="${f?'flight:'+f.id:'view:airlines'}"><span>GATE ${String(i+1).padStart(2,'0')}</span><strong>${f?esc(f.code):'Disponível'}</strong><small>${f?STATES[f.state]:'Classe '+g.class}</small>${f?`<progress max="100" value="${taskProgress(e,f)}"></progress>`:'<i class="gate-free"></i>'}</button>`;}).join('');
 const flights=active.slice(0,6).map(f=>`<button class="flight-strip" data-action="flight:${esc(f.id)}"><span class="flight-logo"><img src="${esc(e.d.airlines.find(a=>a.id===f.airlineId).logo)}" alt="${esc(e.d.airlines.find(a=>a.id===f.airlineId).name)}"></span><span><strong>${esc(f.code)}</strong><small>${esc(e.d.airports.find(a=>a.id===f.destination)?.codes.iata)}</small></span><span class="flight-status">${STATES[f.state]}<progress max="100" value="${taskProgress(e,f)}"></progress></span><span>${f.passengers}<small>pax</small></span><b>↗</b></button>`).join('');
 const checks=e.levelChecks();return `<div class="experience"><section class="apron-scene" style="--scene:url('${asset('bg_apron')}')"><div class="scene-top"><span class="live-pill"><i></i> PÁTIO · ${esc(e.d.balance.weather[s.world.weather].name)}</span>${button('▦ Mapa e construção','view:build','scene-button')}</div><div class="scene-title"><span>${esc(a.name)}</span><h2>${esc(a.codes.iata)}<em>Nível ${s.airport.level}</em></h2></div><div class="scene-shortcuts">${button('⌁ Solo','view:operations','scene-button')}${button('♙ Terminal','view:passengers','scene-button')}${button('✈ Voos','view:flights','scene-button')}</div><div class="gate-deck">${gateCards}</div></section><aside class="decision-rail"><section class="decision-card"><img src="${asset(s.player.avatar)}" alt=""><span class="eyebrow">PRÓXIMA DECISÃO</span><h2>${next.title}</h2><p>${esc(next.text)}</p>${button(next.label+' →',next.action,'primary')}</section><section class="mission-card"><div><span>NÍVEL ${Math.min(10,s.airport.level+1)}</span><b>${checks.filter(x=>x.ok).length}/${checks.length}</b></div><progress max="${Math.max(1,checks.length)}" value="${checks.filter(x=>x.ok).length}"></progress><details><summary>Ver requisitos</summary>${checks.map(c=>`<p class="${c.ok?'positive':''}">${c.ok?'✓':'○'} ${c.label}</p>`).join('')}</details></section><div class="health-pills"><span>♡ Satisfação <b>${Math.round(s.passengersSummary.satisfaction)}%</b></span><span>↗ Caixa <b>${money(s.economy.cash)}</b></span></div></aside></div><section class="traffic-board"><div class="section-title"><h2>Agora no aeroporto <span class="tag">${active.length} voos</span></h2><div>${button('+10 min','advance','small')}${button('Agenda →','view:flights','small')}</div></div><div class="flight-strips">${flights||`<div class="first-route"><span>✈</span><div><strong>Seu primeiro voo começa aqui.</strong><p>Revise uma proposta e assine sua primeira rota.</p></div>${button('Preparar proposta','suggest-route','primary')}</div>`}</div></section><div class="destination-cards">${[['bg_baggage','Operações','Equipamentos e serviços','operations'],['bg_checkin','Passageiros','Filas e satisfação','passengers'],['bg_lounge','Comercial','Expanda suas receitas','commercial']].map(([img,title,sub,id])=>`<button class="destination-card" data-action="view:${id}" style="--scene:url('${asset(img)}')"><span>${title}</span><small>${sub}</small><b>↗</b></button>`).join('')}</div>`;
}

