import {readdir,readFile,writeFile,mkdir,copyFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {validateData} from '../js/core/data.js';
const root=fileURLToPath(new URL('../',import.meta.url));
async function walk(dir){const result=[];for(const e of await readdir(path.join(root,dir),{withFileTypes:true})){const p=dir+'/'+e.name;if(e.isDirectory())result.push(...await walk(p));else result.push(p);}return result;}
const files=['index.html','manifest.webmanifest',...(await Promise.all(['assets','css','data','js'].map(walk))).flat()].sort();
const data=Object.fromEntries(await Promise.all(files.filter(p=>p.startsWith('data/')&&p.endsWith('.json')).map(async p=>[path.basename(p,'.json'),JSON.parse(await readFile(path.join(root,p),'utf8'))])));validateData(data);
for(const p of files.filter(p=>p.endsWith('.js'))){const text=await readFile(path.join(root,p),'utf8');for(const m of text.matchAll(/(?:from\s*|import\s*)['"](\.[^'"]+)['"]/g)){await readFile(path.resolve(root,path.dirname(p),m[1]));}}
const hash=createHash('sha256');for(const p of files)hash.update(await readFile(path.join(root,p)));const version=hash.digest('hex').slice(0,12);
const sw=`// Generated by npm run build. Cache isolated by deployment scope.
const PREFIX='airport-empire:'+self.registration.scope+':';
const CACHE=PREFIX+'${version}';
const FILES=${JSON.stringify(files.map(p=>'./'+p))};
self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(FILES))));
self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith(PREFIX)&&k!==CACHE).map(k=>caches.delete(k))))));
self.addEventListener('fetch',e=>{if(e.request.method!=='GET'||!e.request.url.startsWith(self.registration.scope))return;e.respondWith(caches.open(CACHE).then(async c=>{const hit=await c.match(e.request);if(hit)return hit;try{return await fetch(e.request);}catch(err){if(e.request.mode==='navigate')return c.match('./index.html');throw err;}}));});
`;
await writeFile(path.join(root,'sw.js'),sw);
for(const p of [...files,'sw.js']){const out=path.join(root,'dist',p);await mkdir(path.dirname(out),{recursive:true});await copyFile(path.join(root,p),out);}
console.log(`Build ${version}: ${files.length+1} arquivos públicos em dist/.`);
